name       : rsync
version    : 3.1.3
release    : 11
source     :
    - https://rsync.samba.org/ftp/rsync/src/rsync-3.1.3.tar.gz : 55cc554efec5fdaad70de921cd5a5eeb6c29a95524c715f3bbf849235b0800c0
license    : GPL-3.0
component  : network.clients
summary    : rsync (remote file sync)
description: |
    rsync is a replacement for rcp that has many more features.  It uses the "rsync algorithm" which provides a very fast method for bringing remote files into sync.  It does this by sending just the differences in the files across the link, without requiring that both sets of files are present at one of the ends of the link beforehand.
builddeps  :
    - pkgconfig(popt)
    - acl-devel
    - attr-devel
setup      : |
    %apply_patches
    %configure
build      : |
    %make
install    : |
    %make_install
