name       : rsync
version    : 3.1.2
release    : 9
source     :
    - https://rsync.samba.org/ftp/rsync/src/rsync-3.1.2.tar.gz : ecfa62a7fa3c4c18b9eccd8c16eaddee4bd308a76ea50b5c02a5840f09c0a1c2
license    :
    - GPL-3.0
summary    : rsync (remote file sync)
builddeps  :
    - pkgconfig(popt)
    - acl-devel
    - attr-devel
component  : network.clients
description: |
    rsync is a replacement for rcp that has many more features.  It uses the "rsync algorithm" which provides a very fast method for bringing remote files into sync.  It does this by sending just the differences in the files across the link, without requiring that both sets of files are present at one of the ends of the link beforehand.

    rsync was written by Andrew Tridgell and Paul Mackerras.
setup      : |
    %apply_patches
    %configure
build      : |
    %make
install    : |
    %make_install
