name       : rsync
version    : 3.2.5
release    : 16
source     :
    - https://rsync.samba.org/ftp/rsync/src/rsync-3.2.5.tar.gz : 2ac4d21635cdf791867bc377c35ca6dda7f50d919a58be45057fd51600c69aba
homepage   : https://rsync.samba.org/
license    : GPL-3.0-or-later
component  : network.clients
summary    : rsync (remote file sync)
description: |
    rsync is a replacement for rcp that has many more features.  It uses the "rsync algorithm" which provides a very fast method for bringing remote files into sync.  It does this by sending just the differences in the files across the link, without requiring that both sets of files are present at one of the ends of the link beforehand.
builddeps  :
    - pkgconfig(libacl)
    - pkgconfig(liblz4)
    - pkgconfig(libxxhash)
    - pkgconfig(libzstd)
    - pkgconfig(popt)
setup      : |
    %configure --with-included-zlib=no
build      : |
    %make
install    : |
    %make_install
