name       : rsync
version    : 3.2.3
release    : 14
source     :
    - https://rsync.samba.org/ftp/rsync/src/rsync-3.2.3.tar.gz : becc3c504ceea499f4167a260040ccf4d9f2ef9499ad5683c179a697146ce50e
license    : GPL-3.0-or-later
component  : network.clients
summary    : rsync (remote file sync)
description: |
    rsync is a replacement for rcp that has many more features.  It uses the "rsync algorithm" which provides a very fast method for bringing remote files into sync.  It does this by sending just the differences in the files across the link, without requiring that both sets of files are present at one of the ends of the link beforehand.
builddeps  :
    - pkgconfig(liblz4)
    - pkgconfig(libxxhash)
    - pkgconfig(libzstd)
    - pkgconfig(popt)
    - acl-devel
setup      : |
    %configure --with-included-zlib=no
build      : |
    %make
install    : |
    %make_install
